Gymnasiearbete/my_server/admin/routes.py
from flask import redirect, url_for, request, Blueprint, flash
from flask import render_template as rt
from my_server.admin.utils import admin_required, send_newsletter, is_logged_in, get_current_user
from my_server.models import Product, Picture, Newsletter_Recipients, User, Category
from werkzeug.utils import secure_filename
import os
from my_server import db,app

admin = Blueprint('admin',__name__)

@admin.route('/admin')
@admin_required
def admin_home():
    return rt('admin.html',categories = Category.query.filter(Category.name!='Main').all(), logged_id=is_logged_in(), user=get_current_user())

@admin.route('/admin/category')
@admin_required
def admin_category():
    id = request.args['category_id']
    return rt('admin_products.html', products=Product.query.filter_by(category=id).order_by(Product.id.asc()).all(), pictures = Picture.query.group_by(Picture.product_id).all() ,category_name=Category.query.filter_by(id=id).first().name, logged_id=is_logged_in(), user=get_current_user())


@admin.route('/admin/send_email', methods=['GET','POST'])
@admin_required
def send_email():
    if request.method == 'POST':
        subject = request.form['subject']
        content = request.form['content']
        newsletter = request.form.getlist('newsletter')
        general = request.form.getlist('general')
        recipients = []
        if newsletter != []:
            for recipient in Newsletter_Recipients.query.all():
                recipients.append(recipient.email)
        if general != []:
            for recipient in User.query.all():
                recipients.append(recipient.email)
        if recipients == []:
            flash('Något gick fel, försök igen','warning')
            return rt('send_email.html')
        send_newsletter(subject,content,recipients)
    return rt('send_email.html', logged_id=is_logged_in(), user=get_current_user(),categories = Category.query.filter(Category.name!='Main').all())

@admin.route('/admin/edit', methods=['GET','POST'])
@admin_required
def admin_edit():
    if request.method ==  'POST':
        name = request.form['name']
        description = request.form['description']
        stock = request.form['stock']
        product_id = request.form['id']
        price = request.form['price']
        product = Product.query.filter_by(id=product_id).first()
        if product.name != name:
            product.name = name
        if product.description != description:
            product.description = description
        if product.stock != stock:
            product.stock = stock  
        if product.price != price:
            product.price = price                
        db.session.commit()
        flash('Sparat!')
    elif request.method == 'GET':
        product_id = request.args['product_id']
        if product_id == None:
            return redirect(url_for('admin.admin_home'))
    product = Product.query.filter_by(id=product_id).first()
    pictures = Picture.query.filter_by(product_id=product_id).all()
    return rt('edit_product.html',product = product, pictures=pictures, logged_id=is_logged_in(), user=get_current_user(),categories = Category.query.filter(Category.name!='Main').all())

@admin.route('/admin/edit/upload_picture', methods=['POST'])
def upload_picture():
    product_id = request.form['id']
    file = request.files['file']
    filename = secure_filename(file.filename)
    file.save(os.path.join(app.config['UPLOAD_FOLDER'],filename))
    picture = Picture(product_id=product_id,filepath=f'static/images/{filename}')
    db.session.add(picture)
    db.session.commit()
    return redirect(url_for('admin.admin_edit',product_id=product_id))



@admin.route('/admin/add', methods=['POST','GET'])
@admin_required
def admin_add():
    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        stock = request.form['stock']
        category = request.form['category']
        price = request.form['price']
        if not int(category) > Category.query.count():
            product = Product(name=name,description=description,stock=stock,category=category,price=price,popularity=0)
            db.session.add(product)
            db.session.commit()
            flash('Produkten är tillagd','success')
        else:
            flash('Kategorin finns inte','warning')
            return rt('admin_add.html',product=None, logged_id=is_logged_in(), user=get_current_user(),categories = Category.query.filter(Category.name!='Main').all())
        return redirect(url_for('admin.admin_edit',product_id=product.id))
    return rt('admin_add.html',product=None, logged_id=is_logged_in(), user=get_current_user(),categories = Category.query.filter(Category.name!='Main').all())

Gymnasiearbete/my_server/main/routes.py
from flask import Blueprint
from flask import render_template as rt 
from my_server.models import Category, Product, Picture
from my_server.main.utils import is_logged_in, get_current_user
from random import randint

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/index')
@main.route('/home')
@main.route('/start')
def start():
    products_id = []
    products = []
    pictures = []
    iterations = 10
    i = 0
    while i < iterations:
        id = randint(1,Product.query.count())
        if id not in products_id:
            product = Product.query.filter_by(id=id).first()
            if product is not None:
                products_id.append(id)
                products.append(product)
                i += 1
    for id in products_id:
        pictures.append(Picture.query.filter_by(product_id=id).first())
    return rt('index.html',products=products,pictures=pictures,logged_id=is_logged_in(), user=get_current_user(), categories = Category.query.all())

Gymnasiearbete/my_server/shop/routes.py
from flask import redirect, url_for, session, request, Blueprint, make_response
from flask import render_template as rt
from my_server.shop.utils import is_logged_in, sql_to_list, get_current_user
from my_server.models import Category, Product, Picture
from my_server import db
import json

shop = Blueprint('shop',__name__)

@shop.route('/products')
@shop.route('/products/<category>')
def products(category=0):
    if 'search_data' in session:
        data = session['search_data']
        session.pop('search_data')
        return rt('products.html',products=data)
    elif category == 0:
        products = Product.query.all()
        return rt('products.html',products=products)
    return rt('products.html',products=Product.query.filter_by(category=category).all(),logged_id=is_logged_in(),category=Category.query.filter_by(id=category).first(),user=get_current_user(), categories = Category.query.all())

@shop.route('/product/<id>')
def product(id = 0):
    product = Product.query.filter_by(id=id).first()
    product.popularity = product.popularity + 1
    db.session.commit()
    return rt('product.html',product=product,pictures=Picture.query.filter_by(product_id=id).all(),logged_id=is_logged_in(),user=get_current_user(), categories = Category.query.all())

#inmatning till sökfunktionen är en string -> produkten / kategorins namn
@shop.route('/search_products_categories', methods = ['POST','GET'])
@shop.route('/search_products_categories/<search>')
def search(search = ''):
    if request.method == 'POST':
        search = request.form['parameter']
        if search == '': 
            return json.dumps('empty')
        products = Product.query.filter(Product.name.like('%'+search+'%')).all()
        categories = Category.query.filter(Category.name.like('%'+search+'%')).all()
        return json.dumps((sql_to_list(products),sql_to_list(categories)))
    else:
        session['search_data']=Product.query.filter(Product.name.like('%'+search+'%')).all()
        return redirect(url_for('shop.products'))

@shop.route('/checkout')
def checkout():
    return rt('checkout.html', logged_id=is_logged_in(),user=get_current_user(),categories = Category.query.all())

@shop.route('/payment')
def payment():
    return rt('payment.html', logged_id=is_logged_in(),user=get_current_user(),categories = Category.query.all())

@shop.route('/sort', methods = ['POST'])
def sort_search(category=0,order=''):
    category = request.form['category']
    order = request.form['order']
    if search != '':
        if order == 'ASC':
            products = Product.query.filter(Product.category.like(category)).order_by(Product.price.asc()).all()
            pictures = Picture.query.group_by(Picture.product_id).all()
            return json.dumps((sql_to_list(products),sql_to_list(pictures)))
        elif order == 'DSC':
            products = Product.query.filter(Product.category.like(category)).order_by(Product.price.desc()).all()
            pictures = Picture.query.group_by(Picture.product_id).all()
            return json.dumps((sql_to_list(products),sql_to_list(pictures)))
        elif order == 'POP':
            products = Product.query.filter(Product.category.like(category)).order_by(Product.popularity.desc()).all()
            pictures = Picture.query.group_by(Picture.product_id).all()
            return json.dumps((sql_to_list(products),sql_to_list(pictures)))
    return json.dumps('Fel vid sortering, kontrollera inmatning')

@shop.route('/cookie_products')
def cookie_ajax():
    cookie = json.loads(request.args['data'])
    if cookie == '':
        return json.dumps("error")
    ids = []
    amounts = []
    for product in cookie:
        if product[0] in ids:
            position = ids.index(product[0])
            amounts[position] += product[1]
        else:
            ids.append(product[0])
            amounts.append(product[1])
    products = Product.query.all()
    products_requested = []
    for product in products:
        if product.id in ids:
            product_dict = product.as_dict()
            product_dict['stock']=amounts[ids.index(product.id)]
            products_requested.append(product_dict)
    return json.dumps(products_requested)

Gymnasiearbete/my_server/users/routes.py
from flask import redirect, url_for, request, flash, session, Blueprint
from flask import render_template as rt
from my_server.users.utils import no_login, login_required,send_email, is_logged_in, get_current_user
from my_server import db
from my_server.models import User, Category, Newsletter_Recipients
import datetime
import bcrypt

users = Blueprint('users',__name__)

@users.route('/login', methods=['GET','POST'])
@no_login
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        users = User.query.all()
        for user in users:
            if user.username == username:
                if bcrypt.checkpw(password.encode('utf-8'),user.password):
                    flash('Inloggad','success')
                    session['username'] = username
                    session['logged_in'] = True
                    return redirect(url_for('main.start'))
        flash('Användarnamnet och/eller lösenordet är felaktigt!','warning')
    return rt('login.html',logged_id=is_logged_in(),user=get_current_user(),categories = Category.query.all())

@users.route('/edit_profile', methods=['GET','POST'])
@login_required
def edit_user():
    if request.method == 'POST':
        username = request.form['username']
        name = request.form['name']
        email = request.form['email']
        id = request.form['id']
        user = User.query.filter_by(id=id).first()
        user.username = username
        user.name = name
        user.email = email
        db.session.commit()
        return rt('edit_user.html', user = user,logged_id=is_logged_in(),categories = Category.query.all())
    user_id = request.args['id']
    user = User.query.filter_by(id=user_id).first()
    return rt('edit_user.html', user = user,logged_id=is_logged_in(),categories = Category.query.all())

@users.route('/logout')
@login_required
def logout():
    session.clear()
    flash('Du har loggats ut','info')
    return redirect(url_for('main.start'))

@users.route('/register', methods=['GET','POST'])
@no_login
def register():
    if request.method == 'POST':
        f_name = request.form['fname']
        l_name = request.form['lname']
        username = request.form['uname']
        email = request.form['email']
        password = request.form['password1']
        password2 = request.form['password2']
        current_users = User.query.all()
        for user in current_users:
            if user.username == username:
                flash('Användarnamnet används redan','warning')
                return rt('sign_up.html',categories = Category.query.all())
            elif user.email == email:
                flash('Mailen används redan','warning')
                return rt('sign_up.html',categories = Category.query.all())
        if password == password2:
            hashed_password = bcrypt.hashpw(password.encode('utf-8'),bcrypt.gensalt())
            new_user = User(username=username,name=f_name+' '+l_name,email=email,password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            send_email(new_user)
            flash('Användare skapad, vi har skickat ett bekräftelsemail till din mailadress','success')
            return redirect(url_for('users.login'))
    else:
        return rt('sign_up.html',logged_id=is_logged_in(),user=get_current_user(),categories = Category.query.all())

@users.route('/newsletter/register', methods = ['POST','GET'])
def newsletter_registration():
    if request.method == 'POST':
        email = request.form['email']
        if email == '':
            flash('Du måste skriva in din mail','warning')
            return rt('newsletter_registration.html',logged_id=is_logged_in(),user=get_current_user(),categories = Category.query.all())
        for recipient in Newsletter_Recipients.query.all():
            if recipient.email == email:
                flash('Mailen är redan registrerad','warning')
                return rt('newsletter_registration.html',logged_id=is_logged_in(),user=get_current_user(),categories = Category.query.all())
        nlr = Newsletter_Recipients(email=email)
        db.session.add(nlr)
        db.session.commit()
        flash('Mail är nu registrerad','success')
    return rt('newsletter_registration.html',logged_id=is_logged_in(),user=get_current_user(),categories = Category.query.all())

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def confirm_token(token):
    if not session.get('username') is None:
        current_user = User.query.filter_by(username=session['username']).first()
        if current_user.confirmed:
            flash('Du är redan verifierad','info')
            return redirect(url_for('main.start'))
    user = User.verify_verification_token(token)
    if user is None:
        flash('Felaktig eller gammal länk, försök igen', 'warning')
        return redirect(url_for('main.start'))
    else:
        user.confirmed = True
        db.session.commit()
    flash('Du är nu verifierad!','success')
    return redirect(url_for('main.start'))

Gymnasiearbete/my_server/templates/admin.html
{% extends 'base.html' %}

{% block title %}Admin | buystuff.se{% endblock %}

{% block head%}<link rel="stylesheet" type="text/css" href="..{{ url_for('static', filename='admin_style.css') }}">{% endblock %}

{%block content%}
    <div class="row menu_container">
        {% for category in categories %}
            <div class="col mar5">
                <div class="category_container color-darkernight">
                    <h3 class='color-text-cherry' >{{category.name}}</h3>
                    <a href="{{ url_for('admin.admin_category', category_id = category.id) }}" class="btn btn-cherry">Visa</a>
                </div>            
            </div>
        {% endfor %}
        <div class="col mar5">
            <div class="category_container color-darkernight">
                <h3 class='color-text-cherry'>Nyhetsbrev</h3>
                <a href="{{ url_for('admin.send_email') }}" class="btn btn-cherry">Sicka mail</a>
            </div>            
        </div>
        <div class="col mar5">
            <div class="category_container color-darkernight">
                <h3 class='color-text-cherry'>Lägg till produkt</h3>
                <a href="{{ url_for('admin.admin_add') }}" class="btn btn-cherry">Lägg till</a>
            </div>            
        </div>
    </div>
{% endblock%}

Gymnasiearbete/my_server/templates/admin_add.html
{% extends 'base.html' %}

{% block title %}Admin - lägg till ny produkt| buystuff.se{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="..{{ url_for('static', filename='admin_style.css') }}">
    <script src="{{ url_for('static', filename='product_slideshow.js') }}"></script>
{% endblock %}

{%block content%}
<div class="row">
    <div class="col-sm-7 add-center">
        <form action="{{url_for('admin.admin_add')}}" method="POST">
            <div class="form-group">
                <label for="name">Produktnamn</label>
                <input type="name" class="form-control" name="name" placeholder="Produktnamn">
            </div>
            <div class="form-group">
                <label for="name">Beskrivning</label>
                <textarea class="form-control" rows="10" name="description" placeholder="Beskriving"></textarea>
            </div>
            <div class="form-group">
                <label for="name">Antal</label>
                <input type="number" class="form-control" name="stock" placeholder="Antal i lager">
            </div>
            <div class="form-group">
                <label for="name">Pris</label>
                <input type="number" class="form-control" name="price" placeholder="Pris">
            </div>
            <div class="form-group">
                <label for="name">Kateogri</label>
                <input type="text" class="form-control" name="category" placeholder="Kategori (id)">
            </div>
            <button class="btn btn-cherry" type="submit">Spara</button>
        </form> 
    </div>
</div>
{%endblock%}

Gymnasiearbete/my_server/templates/base.html
<!DOCTYPE html>
<html lang="sv">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="..{{ url_for('static', filename='favicon.png') }}"/>
    <link rel="stylesheet" href="..{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.3/js/all.js"></script>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="..{{ url_for('static', filename='script.js') }}"></script>
    <script src="{{ url_for('static', filename='cookies.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body class="d-flex flex-column min-vh-100 bg-secondary">

<nav id="navbar" class="navbar navbar-expand-sm color-darknight shadow-bottom sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <i class="color-cherry fas fa-bars"></i>
      </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <div class="row flex-grow-1 mr-0px">
            <div class="col-sm-2">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="navbar-brand nav-color" href="{{url_for('main.start')}}">buystuff.se</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-8">
                    <ul class="navbar-nav justify-content-center">
                        <li class="nav-item dropdown w-100">
                            <input class="form-control search-input" type="search"  onkeyup="searchFunction(this.value)" placeholder="Sök" data-toggle="dropdown">
                            <div id="searchDropdownMenu" class="dropdown-menu color-darknight">
                            </div>
                        </li>
                    </ul>
            </div>
            <div class="col-sm-2">
                <ul class="navbar-nav float-r">
                    <li class="nav-item dropdown pc">
                        <a class="nav-link nav-color" data-toggle="dropdown"><i class="fas fa-user mr-1"></i></a>    
                        <div class="dropdown-menu dropdown-menu-right color-darkernight">
                            {% if logged_id == False %}
                            <form class="px-4 py-3" action="{{url_for('users.login')}}" method='post'>
                                <div class="form-group">
                                    <input type="name" class="form-control forms" name="username" placeholder="Användarnamn">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control forms" name="password" placeholder="Lösenord">
                                </div>
                                <button type="submit" class="btn btn-cherry">Logga in!</button>
                            </form>
                            <div class="pt-3 text-center">
                                <small class="text-light">
                                    Eller behöver du ett konto? <a href="{{url_for('users.register')}}" class="ml-2 color-cherry"><br>Skapa ett konto!</a>
                                </small>
                            </div>
                            {% elif logged_id == True %}
                            <a class="dropdown-item profile-color color-white" href="{{url_for('users.edit_user',id=user.id)}}">Inställningar</a>
                            <a class="dropdown-item profile-color color-white" href="{{url_for('users.logout')}}">Logga ut!</a>
                            {% if user.admin == True %}
                            <a class="dropdown-item profile-color color-white" href="{{url_for('admin.admin_home')}}">Admin</a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </li>
                    <li class="nav-item dropdown pc">
                        <a onclick="shoppingCart()" class="nav-link nav-color" data-toggle="dropdown"><i class="fas fa-shopping-cart"></i></a>
                        <div class="dropdown-menu dropdown-menu-right color-darkernight shopping-cart-width" id="shopping-cart">
                        </div>
                    </li>

                    <li class="nav-item phone">
                        <a href="{{url_for('users.login')}}" class="nav-link nav-color"><i class="fas fa-user mr-1"></i></a>    
                    </li>
                    <li class="nav-item phone">
                        <a href="{{url_for('shop.checkout')}}" onclick="shoppingCart()" class="nav-link nav-color"><i class="fas fa-shopping-cart"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

<div class="row flex-grow-1 mr-0px">
    <div class="col-sm-2 color-cherry-bg">
        <ul class="mt-1vh">
            <a class="text-deco" href="{{ url_for('main.start')}}">
                <li class="text-overflow">
                        <h5 class="color-darkernight-text">
                            Hem
                        </h5>
                </li>
            </a>
            {% for category in categories%}
                {% if category.id != 0 %}
                <a class="text-deco" href="{{ url_for('shop.products',category=category.id)}}">
                    <li class="text-overflow">
                            <h5 class="color-darkernight-text">
                                {{category.name}}
                            </h5>
                    </li>
                </a>
                {% endif %}
            {% endfor %}
        </ul>
        {%block left%}{%endblock%}
    </div>
    <div class="col-sm-8 color-darknight ta-c">
        {%block content%}{% endblock%}
        
    </div>
    <div class="col-sm-2 color-cherry-bg">
        {%block right%}{%endblock%}
        <div class="flash-message">
            {% for category, message in get_flashed_messages(with_categories = True) %}
                    <p class="alert alert-{{category}} alert-dismissible fade show mt-3"><button type="button" class="close" data-dismiss="alert">&times;</button> {{ message }} </p>          
            {% endfor %}
        </div>
    </div>
</div>

<div id="accept-cookie" class="container-fluid cookie-confirmation text-center color-darkernight">
    <div class="center">
        <p class="color-cherry">Vi använder oss av cookies!</p>
        <button class="btn btn-cherry" onclick="acceptedCookies()">Ok</button>
    </div>
</div>

<div class="footer-bottom mt-auto color-darkernight jumbotron jumbotron-fluid text-center">
    <h3 class="text-white">Copyrght @ Mathias & Lukas 2021</h3>
    <a href="{{ url_for('users.newsletter_registration') }}">
        <h5 class="text-white">Gå med i nyhetsbrevet</h5>
    </a>
</div>

</body>
</html>

Gymnasiearbete/my_server/templates/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout | buystuff.se{% endblock %}

{%block content%}
    <script>
        window.onload = function() {
            startCookie();
            shoppingCartPage();
        };
    </script>

    <div class="container color-darkernight shopping-cart-page mt-mb-checkout" id="shopping-cart-page">
    </div>
{%endblock%}

Gymnasiearbete/my_server/templates/edit_user.html
{% extends 'base.html' %}

{% block title %}Profil - {{user.name}} | buystuff.se{% endblock %}

{% block head %}
    <script src="{{ url_for('static', filename='product_slideshow.js') }}"></script>
{% endblock %}

{%block content%}
    <div class="container mt-1vh">
        <form action="{{url_for('users.edit_user')}}" method="POST">
            <div class="form-group">
                <label for="username">Användarnamn</label>
                <input type="text" class="form-control" name="username" value="{{user.username}}">
            </div>
            <div class="form-group">
                <label for="name">Namn</label>
                <input type="name" class="form-control" name="name" value="{{user.name}}">
            </div>
            <div class="form-group">
                <label for="email">Mailadress</label>
                <input type="text" class="form-control" name="email" value="{{user.email}}">
            </div>
            <div class="form-group">
                <input type="hidden" name="id" value="{{user.id}}">
            </div>
            <button class="btn btn-outline-primary" type="submit">Spara</button>
        </form> 
    </div>
{%endblock%}

Gymnasiearbete/my_server/templates/index.html
{% extends 'base.html'%}

{% block title %}buystuff.se{% endblock %}

{% block head %}
    <script src="{{ url_for('static', filename='start_slideshow.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="slideshow-container-start">
                {% for picture in pictures %}    
                    <div class="mySlides2 center">
                        <a href="{{url_for('shop.product', id=products[loop.index-1].id)}}"><img class="img-responsive" src="/{{picture.filepath}}" alt="{{picture[0]}}"></a>
                    </div>
                {% endfor %}
                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" onclick="plusSlides(1)">&#10095;</a>
            </div>

            <div class="ta-c">
                {% for i in range(pictures|length)%}
                <span class="dot" onclick="currentSlide({{i+1}})"></span>
                {%endfor%}
            </div>
        </div>
    </div>

    
    <div id="products" class="row">
        {% for product in products %}
        <div class="col mar5"><a href="{{url_for('shop.product', id=product.id)}}" class="color-text-cherry text-deco">
            <div class="product"><img class="center" src=/{{pictures[loop.index-1].filepath}} alt=""></div>
            <h3>{{product.name}}</h3>
        </a></div>
        {% endfor %}
    </div>
{% endblock %}

Gymnasiearbete/my_server/templates/login.html
{% extends 'base.html' %}

{% block title %}Login | buystuff.se{% endblock %}

{%block content%}
<div class="container mt-mb-login">
    <form action="{{url_for('users.login')}}" method='post'>
        <div class="form-group">
            <input type="name" class="form-control forms" name="username" placeholder="Användarnamn">
        </div>
        <div class="form-group">
            <input type="password" class="form-control forms" name="password" placeholder="Lösenord">
        </div>
        <button type="submit" class="btn btn-cherry">Logga in!</button>
    </form>
    <div class="pt-3">
        <small class="text-muted">
            Eller behöver du ett konto? <a href="{{url_for('users.register')}}" class="ml-2 color-cherry">Skapa ett konto!</a>
        </small>
    </div>
</div>
{% endblock%}

Gymnasiearbete/my_server/templates/newsletter_registration.html
{% extends 'base.html' %}

{%block content%}
<div class="container mt-1vh">
    <form action="{{url_for('users.newsletter_registration')}}" method='post'>
        <div class="form-group">
            <input type="email" class="form-control forms" name="email" placeholder="Email">
        </div>
        <button type="submit" class="btn btn-cherry">Gå med!</button>
    </form>
</div>
{% endblock%}

Gymnasiearbete/my_server/templates/send_email.html
{% extends 'base.html' %}

{% block title %}Admin | buystuff.se{% endblock %}

{% block head %}<link rel="stylesheet" type="text/css" href="..{{ url_for('static', filename='admin_style.css') }}">{% endblock %}

{%block content%}
    <div class="container">
        <form action="{{url_for('admin.send_email')}}" method='post' class="email-form">
            <div class="form-group">
                <input type="name" class="form-control" name="subject" placeholder="Ämne">
            </div>
            <div class="form-group">
                <textarea class="form-control" rows="10" name="content" placeholder="Innehåll"></textarea>
            </div>
            <div class="form-group display-flex email-checkbox">
                <label for="newsletter">Nyhetsbrev</label>
                <input type="checkbox" class="form-control forms" id="newsletter" name="newsletter" value="True">
            </div>
            <div class="form-group display-flex email-checkbox">
                <label for="general">Generelt</label>
                <input type="checkbox" class="form-control forms" id="general" name="general" value="True">
            </div>
            <button type="submit" class="btn btn-cherry">Skicka mail</button>
        </form>
    </div>
{%endblock%}